### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by xSyki** [rsanchez/css-color-extractor#7]
Hi, Do you plan to support extracting colors from variables?

Example:
```css
:root {
  --white-background: #ffffff;
}

.test {
  color: var(--white-background);
  background-color: blue;
}
```

Of course, the blue color was extracted, unfortunately #ffffff not.

**Comment by xSyki** [comment]
From what I can see, the package also does not support the filter property.

Example:
```css
.test {
  filter: drop-shadow(30px 10px 4px #4444dd);
}
```

A very nice package that can be useful to me. If you don't have time to develop it or need help, let me know.
